# -*- coding: utf-8 -*-
"""Passport Verification System)pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgOeWtaH7CogtrcIRjMNThF9tJOiDEu6
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf

train_data = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/MyDrive/passport_dataset/train",
    image_size=(224,224),
    batch_size=32
)

test_data = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/MyDrive/passport_dataset/test",
    image_size=(224,224),
    batch_size=32
)

import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "train" in dirs or "test" in dirs:
        print(root)

train_data = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/MyDrive/Cv/passport_dataset/train",
    image_size=(224,224),
    batch_size=32
)

import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "real" in dirs or "fake" in dirs:
        print(root)

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "passport" in root.lower():
        print(root)

import os

base = "/content/drive/MyDrive/passport_dataset"

os.makedirs(base + "/train/real", exist_ok=True)
os.makedirs(base + "/train/fake", exist_ok=True)
os.makedirs(base + "/test/real", exist_ok=True)
os.makedirs(base + "/test/fake", exist_ok=True)

print("Dataset created ✔")

train_data = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/MyDrive/passport_dataset/train",
    image_size=(224,224),
    batch_size=32
)

import os

print(os.path.exists("/content/drive/MyDrive/passport_dataset/train"))
print(os.listdir("/content/drive/MyDrive/passport_dataset"))

import os

print(os.listdir("/content/drive/MyDrive/passport_dataset/train"))

import os

print("REAL:", os.listdir("/content/drive/MyDrive/passport_dataset/train/real"))
print("FAKE:", os.listdir("/content/drive/MyDrive/passport_dataset/train/fake"))

train_data = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/MyDrive/passport_dataset/train",
    image_size=(224,224),
    batch_size=32
)

import tensorflow as tf

train_data = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/MyDrive/passport_dataset/train",
    image_size=(224,224),
    batch_size=32
)

test_data = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/MyDrive/passport_dataset/test",
    image_size=(224,224),
    batch_size=32
)

normalization = tf.keras.layers.Rescaling(1./255)

train_data = train_data.map(lambda x, y: (normalization(x), y))
test_data = test_data.map(lambda x, y: (normalization(x), y))

from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, 3, activation='relu', input_shape=(224,224,3)),
    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),

    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_data,
    validation_data=test_data,
    epochs=10
)

loss, acc = model.evaluate(test_data)
print("Accuracy:", acc)

import numpy as np
from tensorflow.keras.preprocessing import image

img = image.load_img("passport.jpg", target_size=(224,224))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)

pred = model.predict(img)

if pred[0][0] > 0.5:
    print("⚠️ مزيف")
else:
    print("✅ حقيقي")

from google.colab import files
files.upload()

import os

print(os.listdir("/content"))

from tensorflow.keras.preprocessing import image
import numpy as np

img = image.load_img("IMG_6713.png", target_size=(224,224))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)

prediction = model.predict(img)

if prediction[0][0] > 0.5:
    print("⚠️ مزيف")
else:
    print("✅ حقيقي")

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

# تحميل الصورة
img_path = "IMG_6713.png"

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

# لو نموذجك مدرّب (مهم)
prediction = model.predict(img_array)[0][0]

# تحويلها لنسبة
fake_prob = float(prediction) * 100
real_prob = (1 - float(prediction)) * 100

# عرض الصورة
plt.imshow(img)
plt.axis("off")
plt.show()

# طباعة النتيجة
print("🧠 تحليل الصورة:")
print(f"⚠️ نسبة التزوير: {fake_prob:.2f}%")
print(f"✅ نسبة الحقيقي: {real_prob:.2f}%")

if fake_prob > 70:
    print("🚨 مزيف بنسبة عالية")
elif fake_prob > 40:
    print("⚠️ مشكوك فيه")
else:
    print("✅ يبدو حقيقي")

!pip install gradio

import gradio as gr
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# دالة التنبؤ
def predict_passport(img):

    img = img.resize((224,224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)[0][0]

    fake_prob = float(prediction) * 100
    real_prob = (1 - float(prediction)) * 100

    result = "⚠️ مزيف" if fake_prob > 50 else "✅ حقيقي"

    return img, f"""
    🧠 النتيجة: {result}
    ⚠️ نسبة التزوير: {fake_prob:.2f}%
    ✅ نسبة الحقيقي: {real_prob:.2f}%
    """

# واجهة المستخدم
app = gr.Interface(
    fn=predict_passport,
    inputs=gr.Image(type="pil"),
    outputs=[
        gr.Image(),
        gr.Textbox()
    ],
    title="🛂 كشف تزوير جواز السفر بالذكاء الاصطناعي",
    description="ارفع صورة جواز السفر وسيتم تحليلها مباشرة"
)

app.launch()